---
- name: provision
  hosts: all
  gather_facts: no
  become: true
  become_user: root
  tasks:
    - name: Wait until ssh is available
      wait_for_connection:
        delay: 90
        sleep: 3
        timeout: 400
    - command: hostname
      register: h
    - debug: msg="{{ h.stdout }}"

    - name: copy mxnet artifacts
      copy:
        src: "{{ item }}"
        dest: mxnet_dist/
      with_fileglob: "/work/mxnet/build/*.whl"

    - name: copy runtime_functions.py
      copy:
        src: "/work/runtime_functions.py"
        dest: .
    - file:
        path: runtime_functions.py
        mode: 0755

    - name: 'run tests'
      command: ./runtime_functions.py run_unittests_python3_qemu_
      async: 1000
      poll: 0
      register: tests

    - name: 'wait for tests to finish'
      async_status: jid={{ tests.ansible_job_id }}
      register: job_result
      until: job_result.finished
      # 6h timeout
      retries: 2160
      delay: 10

#
#    - name: copy runtime_functions.py
#      copy:
#        src: runtime_functions.py
#        dest: mxnet/runtime_functions.py
#        mode: 0775

#    - name: Execute tests
#      command: ./runtime_functions.py run_unittests_python
#      chdir: mxnet/
#      async: 86400
#      poll: 30
#
