---
- name: provision QEMU VM
  hosts: all
  gather_facts: no
  become: true
  become_user: root
  tasks:
    - name: Wait until ssh is available
      wait_for_connection:
        delay: 0
        sleep: 3
        timeout: 400
    - command: hostname
      register: h
    - debug: msg="{{ h.stdout }}"

    - name: copy mxnet artifacts
      copy:
        src: "{{ item }}"
        dest: mxnet_dist/
      with_fileglob: "/work/mxnet/build/*.whl"

    - name: copy runtime_functions.py
      copy:
        src: "/work/runtime_functions.py"
        dest: .
    - file:
        path: runtime_functions.py
        mode: 0755


